library("robotstxt")
p=paths_allowed("https://www.91mobiles.com/best-mobiles-in-india")
#Reading the website
library(rvest)
web = read_html("https://www.91mobiles.com/best-mobiles-in-india")
library(dplyr)

name = web%>%html_nodes(".name")%>%html_text()
View(name)
RAM<-web%>%html_nodes(".left:nth-child(1) label:nth-child(5)")%>%html_text()
View(RAM)
camera<-web%>%html_nodes(".left:nth-child(3) label:nth-child(5)")%>%html_text()
View(camera)
battery<-web%>%html_nodes(".left:nth-child(4) label:nth-child(1)")%>%html_text()
View(battery)
price<-web%>%html_nodes(".price_padding")%>%html_text()
View(price)
processor<-web%>%html_nodes(".left:nth-child(1) label:nth-child(3)")%>%html_text()
View(processor)
display<-web%>%html_nodes(".left:nth-child(2) label:nth-child(1)")%>%html_text()
View(display)
mobiles_specs<-data.frame(name,RAM,display,battery,camera,processor,price)
View(mobiles_specs)
#Analyze
dim(mobiles_specs)
str(mobiles_specs)
mobiles_specs$RAM<-gsub("RAM","",mobiles_specs$RAM)
View(mobiles_specs)
mobiles_specs$camera<-gsub("Camera","",mobiles_specs$camera)
View(mobiles_specs)
